Feature/fast epr wavelettree
xxsds/sdsl-lite pull request #75
Opened 2020-07-15 16:03 UTC by rrahn

Finalises and improves the original PR for the EPR dictionary.
Supersedes #70 

This is a more efficient re-implementation of the rank_support_int_v which is roughly 20% faster than SeqAn2

```console
Run on (8 X 2600 MHz CPU s)
CPU Caches:
  L1 Data 32K (x4)
  L1 Instruction 32K (x4)
  L2 Unified 262K (x4)
  L3 Unified 6291K (x1)
Load Average: 2.72, 2.72, 2.78
---------------------------------------------------------------------------
Benchmark                                 Time             CPU   Iterations
---------------------------------------------------------------------------
rank<seqan::Dna>/100                   37.2 ns         37.1 ns     18891297
rank<seqan::Dna>/10000                 37.1 ns         37.0 ns     18946725
rank<seqan::Dna>/1000000               42.2 ns         41.4 ns     17608734
rank<seqan::Dna>/100000000             97.6 ns         97.2 ns      7505173
rank<seqan::AminoAcid>/100             33.3 ns         33.2 ns     20939026
rank<seqan::AminoAcid>/10000           33.8 ns         33.6 ns     20824285
rank<seqan::AminoAcid>/1000000         80.6 ns         80.3 ns      8981613
rank<seqan::AminoAcid>/100000000        173 ns          173 ns      4088188
```
 And the epr rank:

```console
Run on (8 X 2600 MHz CPU s)
CPU Caches:
  L1 Data 32K (x4)
  L1 Instruction 32K (x4)
  L2 Unified 262K (x4)
  L3 Unified 6291K (x1)
Load Average: 2.44, 2.63, 2.74
-------------------------------------------------------------
Benchmark                   Time             CPU   Iterations
-------------------------------------------------------------
rank<4>/100              29.5 ns         29.3 ns     22639581
rank<4>/10000            28.8 ns         28.8 ns     24426074
rank<4>/1000000          30.0 ns         29.9 ns     23663278
rank<4>/100000000        82.0 ns         81.7 ns      9390931
rank<27>/100             25.1 ns         25.0 ns     27870347
rank<27>/10000           25.2 ns         25.2 ns     27414750
rank<27>/1000000         76.9 ns         76.6 ns      9309253
rank<27>/100000000        142 ns          141 ns      5190414
```

2020-07-21 15:23 UTC, h-2 commented
Thank you for working on this first of all!

These are my small benchmark results. It should be noted that none of these use the official search interface and instead include code that avoids allocations inside the search (see seqan/seqan3#1991 ). Otherwise, additional slowdown occurs.

Also, this uses SeqAn3 from around February since later changes broke the interfaces I added to avoid said allocations.

## 12 Threads 

|                                                         | lambda2 | lambda3 WT | lambda3 EPR Seiler | lambda3 EPR Rahn |
|------------------------------------------------|-------------:|------------------:|----------------------------:|----------------------------:|
| Wall-clock time of search+extend | 22s         | 81s                | 43s                           |  32s                         |
| CPU-time of search-step               | 170s         | 789s            |  389s                         |  249s                         |
| Index size  (on-disk)                      | 397 MB   | 361 MB       | 711 MB                       | 736 MB                    |
| Max. RSS                                       |  1018 MB   |  608 MB       |  998 MB                       |  1052 MB                    |

Reading of database and pre-processing is not included in the wall clock time [deserialisation is a lot slower than SeqAn2's btw, around 5x, but this is somewhat expected].

CPU-time is counted within the program so not 100% accurate, but it's a good indication and reflects total wall clock times.

## 6 Threads

|                                                         | lambda2 | lambda3 WT | lambda3 EPR Seiler | lambda3 EPR Rahn |
|------------------------------------------------|-------------:|------------------:|----------------------------:|----------------------------:|
| Wall-clock time of search+extend | 30s         | 114s                | 58s                           |  45s                         |
| CPU-time of search-step               | 126s         | 595s            |  277s                         |  193s                         |
| Index size    (on-disk)                      | 397 MB   | 361 MB       | 711 MB                       | 736 MB                    |
| Max. RSS                                       | 900 MB   | 568 MB       |  932 MB                       |  985 MB                    |



## Conclusion

The new branch significantly improves performance for Lambda. But it is still notably slower than lambda2/SeqAn2. I know that lazy-loading and online-processing of sequences in lambda3 adds about 10% run-time, but currently we are still at +50% run-time. All other steps that happen as part of the wall-clock time (alignment, output) are using the same SeqAn2-based code in all versions of Lambda.
So even if we allot an additional +10% to unknown sources, it seems that search itself incurs +30% runtime. I have done no profiling, so I don't want to guess where this comes from, but it could very well be something outside the rank computation which you obviously improved quite a bit!

In summary: This PR is a significant improvement and I wholeheartedly support merging it in the current form. But the search as a whole still hasn't caught up to SeqAn2 and more research in the area needs to be done.

P.S: The serialised index of the new EPR is much bigger than in SeqAn2, although this is not reflected in memory usage. Any clue why?

2020-10-30 10:03 UTC, eseiler requested changes

2020-10-30 10:03 UTC, eseiler commented on test/wt_byte_epr_test.cpp
> +namespace
There's a `wt_byte_test`. Can you check if it works if you add it there to both Implementation sets (FULL_TEST_SUITE) ?

2021-11-11 15:37 UTC, eseiler commented
From what I've seen, we cannot use the `wt_byte_test` directly as we do not return the original ranks.
E.g. `T=mississippi` (example01.txt).
Both EPR and other WTs have `sigma=5`, but the EPR return ranks `0-4`, while the other WTs return the original `char` rank.

2021-11-12 07:40 UTC, rrahn commented
@eseiler many thanks for all your efforts!!! That totally 🤘 
Please, let me know if there is anything you'd like to discuss regarding the design.

2021-11-15 13:25 UTC, eseiler commented
@rrahn @h-2 

I'll try to have a closer look once again this week (last week I just focused on getting CI to work).
If I don't discover major things, **would there be any objections to merging this PR**?

2021-11-15 18:25 UTC, rrahn commented
I think it should be fine for now, since it can be tested thoroughly before the next release.
Seems that  there are still some improvements regarding space used for the serialised index as well as performance with respect to SeqAn2.

2021-11-16 09:03 UTC, eseiler approved these changes

2021-11-16 09:03 UTC, merged

2021-11-16 12:07 UTC, h-2 commented
Thank you both for your work on this!